### ISSUE TITLE
Add a platform-independent timeout to the "until" line in start_fair_registry

### ISSUE THREAD

**Issue by alahiff** [FAIRDataPipeline/data-registry#103]
We should have a timeout for https://github.com/FAIRDataPipeline/data-registry/blob/main/scripts/start_fair_registry#L9, otherwise it could get stuck forever.

**Comment by richardreeve** [comment]
We probably don't want this in the 1.0 release, so I've added it to the milestone...

**Comment by alahiff** [comment]
Fixed in https://github.com/FAIRDataPipeline/data-registry/commit/24514dde4e8a033ce3f3328d632e5bb0f7ed24cb. Will only wait for 3.5 seconds then give an error message and exit if the local registry doesn't work.
