### ISSUE TITLE
Add an option to localregistry.sh to allow different branches/tags to be used

### ISSUE THREAD

**Issue by alahiff** [FAIRDataPipeline/data-registry#104]

**Comment by richardreeve** [comment]
Could the default be to download the latest full release version tagged on github? I see from [this stackoverflow question](https://stackoverflow.com/questions/14866528/how-can-i-grab-the-latest-stable-repo-version-from-the-github-api) that this link provides the json for all of the releases:

https://api.github.com/repos/FAIRDataPipeline/data-registry/releases

We can then filter for `prerelease==false` and download by that tag. So we could have three command line switches, all relatively simple:

0. by default, download the latest non-prerelease
1. `--prerelease` - download the latest prerelease or release (i.e. do not filter by `!prerelease`)
2. `--tag=X.xxx` - download a specific tag
3. `--branch=yyy` - download a specific branch

**Comment by alahiff** [comment]
We can just do something like this:

Example getting the latest release (not a draft, not a pre-release):
```
$ curl --silent "https://api.github.com/repos/docker/compose-cli/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
v1.0.17
```
Example getting the latest release, including pre-releases etc:
```
$ curl --silent "https://api.github.com/repos/docker/compose-cli/releases" | grep -Po '"tag_name": "\K.*?(?=")' | head -n 1
v2.0.0-beta.6
```

`docker/compose-cli` was selected as an example because there have a number pre-releases ahead of the latest stable release.

**Comment by richardreeve** [comment]
Great! That sounds pretty easy. A tiny note of caution though... is there any guarantee that the second example gives the releases in the right order? There may well be.

**Comment by alahiff** [comment]
Implemented in https://github.com/FAIRDataPipeline/data-registry/commit/4949496c7cfe72812737cb9c10ae0cc9f0c60684.

Now it works like this:
* By default the latest full release is used
* `-b|--branch`: specify a branch to use
* `-m|--main`: use the current main branch (quicker than having to write `-b main`)
* `-t|--tag`: specify a tag to use
* `-p|--prerelease`: use the latest release, even if it's a pre-release

(not implemented on data.scrc.uk yet).

**Comment by alahiff** [comment]
> Great! That sounds pretty easy. A tiny note of caution though... is there any guarantee that the second example gives the releases in the right order? There may well be.

Unfortunately I don't think there is any guarantee mentioned in the documention, but it does appear to return things ordered by date, e.g. for my example:
```
v2.0.0-beta.6
v2.0.0-beta.5
v2.0.0-beta.4
v1.0.17
v2.0.0-beta.3
v1.0.16
v1.0.15
v1.0.14
v1.0.13
v1.0.12
v1.0.11
v1.0.10
v1.0.9
v1.0.8
v1.0.7
v1.0.6
v1.0.5
v1.0.4
v1.0.3
v1.0.2
v1.0.1
v1.0.0
v0.1.23
v0.1.22
v0.1.21
v0.1.20
v0.1.19
v0.1.18
v0.1.18-beta1
v0.1.17
```

I guess it depends on what people assume "getting the latest release" actually means. If it's the release with the largest number then sorting is easy (e.g. `sort -r -V` works correctly with versions). if we want to be really careful and do it by date, then we would need to order by the created_at or published_at timestamps from the JSON (easy in Python, in bash not quite so easy).

**Comment by richardreeve** [comment]
`sort -r -V` seems like a good solution - I was assuming that it's the highest number we wanted, but you're right that it look like it's mostly fine anyway.

**Comment by alahiff** [comment]
Added `sort -r -V` in https://github.com/FAIRDataPipeline/data-registry/commit/33fc58ecc41452e1b2262f07bc24d1d383b85cd1, just to be sure it works consistently.

**Comment by richardreeve** [comment]
Presumably we can close this once #111 merges with the bug fix.

**Comment by alahiff** [comment]
Closing, since https://github.com/FAIRDataPipeline/data-registry/pull/111 has fixed the issue on MacOS
