### ISSUE TITLE
Delay in web pages updating in local registry

### ISSUE THREAD

**Issue by alahiff** [FAIRDataPipeline/data-registry#110]
The web pages (not the REST API) have caching enabled and are only updated every 5 minutes. This is somewhat confusing and annoying in a local registry and so probably should be disabled in this situation.

**Comment by alahiff** [comment]
Fixed in https://github.com/FAIRDataPipeline/data-registry/commit/ef4a6120378992809915644f4fd1e081fe9cde48

**Comment by richardreeve** [comment]
Ah, that's what was going on when I was playing with it yesterday - I thought I was going mad!
