### ISSUE TITLE
Can't assume access to .fair directory

### ISSUE THREAD

**Issue by mjb3** [FAIRDataPipeline/data-registry#126]
We cannot assume access to the .fair directory going forward owing to the nature of [future] requirements. This will affect any current functionality in dependent packages that relies on access to the directory, including the token; file database; and scripts.

NB. I'm raising this issue at Alys and Richard's request - please contact them for details as I don't fully understand the details of the future circumstance/requirement that makes this necessary.

**Comment by RyanJField** [comment]
The CLI and install scripts address this, While the default installation is ~/.fair this can be changed in all scripts and the CLI.
