### ISSUE TITLE
If graphviz is not installed, you get an internal server error

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#130]
If graphviz is not installed, when you try to look at a prov report you get an internal server error due to:
```
Exception Type: FileNotFoundError at /api/prov-report/1/
Exception Value: [Errno 2] "dot" not found in path.
```
It would be good if we could give a nicer error than a 500, and perhaps when the local registry is installed we could check for the existence of `dot` and if it's not there give a warning message.

_Originally posted by @alahiff in https://github.com/FAIRDataPipeline/data-registry/issues/128#issuecomment-909020652_

**Comment by richardreeve** [comment]
@alahiff - I presume this isn't something that can be installed during data-registry installation? What happens with the other registry dependencies?

**Comment by alahiff** [comment]
@richardreeve We could try to install it, but would need to use `sudo` and would need to handle different platforms (e.g. use `yum` for RHEL/CentOS, `apt` for Ubuntu, ...). So far we haven't been doing anything that requires sudo access.

**Comment by alahiff** [comment]
With these commits (https://github.com/FAIRDataPipeline/data-registry/pull/128/commits/bac4ac84914c5dc34789d809c1d9e3017a08be8b, https://github.com/FAIRDataPipeline/data-registry/pull/128/commits/7f20e4dc529d99be489b000edc64bacbc1551ae9) `start_fair_registry` now gives this warning if necessary:
```
WARNING: Graphviz is not installed, so provenance report images are not available
```
and looking at an image will return status 400 and the text `None` rather than a 500. Will try to improve the text to give a better message...

**Comment by antony-wilson** [comment]
Would 415 "Unsupported Media Type" be better?

**Comment by alahiff** [comment]
Good idea, makes much more sense! Implemented in https://github.com/FAIRDataPipeline/data-registry/commit/254d9d2fe3f84093ff9753f28a2362642d0cd4ed

**Comment by antony-wilson** [comment]
Hi @alahiff, thinking about it some more it might be better to remove `JPEGRenderer` and `SVGRenderer` from the `ProvReportView` class if `Graphviz` is not installed. Then they will not appear in the drop down on the web page or in the list of `renders` when you do an `options` request. 
I've put the necessary changes on a branch [graphviz](https://github.com/FAIRDataPipeline/data-registry/tree/graphviz) for you to look at
