### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#143]
Would it also be possible to get a `resize` parameter? When I try to shrink the image in R it becomes blurry and out of focus.

_Originally posted by @soniamitchell in https://github.com/FAIRDataPipeline/data-registry/issues/139#issuecomment-920089351_

@antony-wilson suggested using `dot.set_resolution`...

**Comment by antony-wilson** [comment]
Having looked again I see that `resolution` is a synonym for `dpi` . I think `dpi` is more explicit so I'll add an optional parameter of `dpi`
