### ISSUE TITLE
Failed downloads of files in local registry

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#149]
I'm playing with the Java implementation - I've put instructions for running it in the README at https://github.com/FAIRDataPipeline/javaSimpleModel - and it's all working well, but I'm having a problem downloading files via the registry download links.

After running it, when I go to `http://localhost:8000/data_product/2` and look at the link `link` next to **Download**, the link address is `http://localhost:8000/data_product/richardr:SEIRS_model/results/model_output@0.0.1`, which looks right, but that redirects to `http://localhost:8000/Users/richardr/.fair/data/richardr/SEIRS_model/results/model_output/0.0.1.csv` rather than `file:///Users/richardr/.fair/data/richardr/SEIRS_model/results/model_output/0.0.1.csv`. This seems to be because the storage root is `/Users/richardr/.fair/data/`, without a `file://` prepended. I wonder if it's possible to fix that in the registry so the download links are correct?

At the same time, when I go to `http://localhost:8000/data_product/1` and look at the link `link` next to **Download** again, the address is `http://localhost:8000/data_product/PSU:SEIRS_model/parameters@1.0.0`, which again looks right, but that doesn't redirect at all and just gives **Bad Request (400)** rather than `file:///Users/richardr/.fair/data/PSU/SEIRS_model/parameters/1.0.0.csv`. It seems like that link should redirect correctly, and certainly when I paste that into the web browser it works... any thoughts?

*Note I've had to update FAIR-CLI to get to this point due to a couple of small bugs there, so you'll need to pull that repo to reproduce this exactly.*

**Comment by alahiff** [comment]
We should ensure that there is only one way to define a local storage root, so users don't need to pick one of `/Users/richardr/.fair/data/` or `file:.///Users/richardr/.fair/data/`. Issue created: https://github.com/FAIRDataPipeline/data-registry/issues/150

**Comment by richardreeve** [comment]
We're moving to fixing the DPAPIs so that protocol is always mentioned in the storage roots (per #150). In fact, DPAPIs shouldn't be creating storage roots, and `fair` is doing this correctly I think, but delays in implementing `fair` meant the DPAPIs started creating protocol-less storage roots by accident. For the time being silently fixing the problem in the registry (as you are in #151) is great.
