### ISSUE TITLE
Not selecting the right tag

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#202]
@RyanJField Something is going wrong here - it's picking the oldest tag, and ignoring instructions to pick a different one:
https://github.com/FAIRDataPipeline/data-registry/blob/58aa06f61ee5f37b92183f25c4c785668bf90bb1/static/remoteregistry.ps1#L139-L150

**Comment by richardreeve** [comment]
There's also something odd that the directory here is a `registry` subdirectory of the one you pick, whereas I think on linux it's just the directory:

https://github.com/FAIRDataPipeline/data-registry/blob/58aa06f61ee5f37b92183f25c4c785668bf90bb1/static/remoteregistry.ps1#L52-L61

**Comment by richardreeve** [comment]
These needs commas after them too I think:
https://github.com/FAIRDataPipeline/data-registry/blob/58aa06f61ee5f37b92183f25c4c785668bf90bb1/scripts/start_fair_registry_windows.ps1#L7-L8

**Comment by RyanJField** [comment]
> There's also something odd that the directory here is a `registry` subdirectory of the one you pick, whereas I think on linux it's just the directory:
> 
> https://github.com/FAIRDataPipeline/data-registry/blob/58aa06f61ee5f37b92183f25c4c785668bf90bb1/static/remoteregistry.ps1#L52-L61

You're right this differs from the bash version, as I had to remove the registry folder to get it to work on the CI, I'll change this.
