### ISSUE TITLE
Make changes to the registry schema to facilitate sync process

### ISSUE THREAD

**Issue by alysbrett** [FAIRDataPipeline/data-registry#23]

**Comment by richardreeve** [comment]
We will need a _"staging"_ / _"commit"_ table in the local schema that notes which entries in which tables in the local registry need to be synced back to the remote registry. It may also need to note which entries in the local schema are already synced?

Alternatively, every table in the local schema could have a column that says whether it is local-only, remote, or to-be-synced...

Or something cleverer!

**Comment by RyanJField** [comment]
All metadata will be synced, only the files of `data_product`s marked as public will be synced.
