### ISSUE TITLE
Change ExternalObject so it links to a DataProduct rather than an Object

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [FAIRDataPipeline/data-registry#43]

**Comment by nathan-cummings-ukaea** [comment]
This change will also involve changes to the UI of the registry. At the moment, `DataProduct`s and `ExternalObject`s are in separate tables on the homepage. How would we like the `ExternalObject`s displayed now that they are to be directly associated with `DataProduct`s? @richardreeve @alahiff

**Comment by richardreeve** [comment]
I think these remain as two independent tables in the web interface @nathan-cummings-ukaea - we just reference the data product from the external object entry now.

**Comment by nathan-cummings-ukaea** [comment]
Ok, so currently the UI suggests that external objects and data products are different things.
![image](https://user-images.githubusercontent.com/55384390/122895467-0af30b00-d340-11eb-9ba4-9fefac5afd64.png)

Are we happy for the titles of those table to stay the same, or would it be better to re-label them. 'Internal Data' and 'External Data' perhaps?

**Comment by richardreeve** [comment]
I'm pretty easy either way. I'm imagining that the second half of the year will involve playing around a lot with this website to make it easier to use and understand, so feel free to start that now...

**Comment by nathan-cummings-ukaea** [comment]
I've made a branch and made a bunch of the necessary changes for this. There are still a few issues to iron out which I've informed @alahiff about, in case he has time to look at it before I do.

**Comment by alahiff** [comment]
I've made a commit to fix a 500 error when going to the `object` API endpoint (there was still a connection between objects and external objects): https://github.com/FAIRDataPipeline/data-registry/commit/8a7daffc378cfccd2fedf0444ed61ea22365c0eb

**Comment by alahiff** [comment]
@richardreeve Even though the web UI displays data products, external objects and code repo releases, it's actually only displaying objects. When external objects are no longer directly attached to an object, the view no longer works and gives an exception as it assumes that everything has an assocated object.

**Comment by alahiff** [comment]
With this commit https://github.com/FAIRDataPipeline/data-registry/commit/2b75f854fcecd5b908bd4cfa10ba9711c5ebc332#diff-98f4560b884627ff362583b7ebe2d14b6696968274da8098aa26993eae760f01 `DataProduct`s have connections to external objects (a read-only field).

**Comment by richardreeve** [comment]
Oh, I see. Well, we'll worry about that later I guess!

**Comment by richardreeve** [comment]
Leaving the rest in #79.
