### ISSUE TITLE
Automatically create ObjectComponent(whole_object=True) when creating an Object

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [FAIRDataPipeline/data-registry#45]
Also make the whole_object field read-only, such that any further ObjectComponents associated with that Object will have whole_object=False.

**Comment by richardreeve** [comment]
@nathan-cummings-ukaea How is this coming along - is there a linked PR?

**Comment by alahiff** [comment]
In the pull request whenever an `Object` is created an `ObjectComponent` is automatically created with name `whole_object` and with the `whole_object` field set to `True`.

**Comment by alahiff** [comment]
Still need to change the `whole_object` field to be read-only, i.e. automatically-generated. The value should be `True` for the automatically-generate whole object `ObjectComponent`, but `False` for everything else.

**Comment by alahiff** [comment]
`whole_object` is now automatically-generated.

@richardreeve I think this is now complete

**Comment by richardreeve** [comment]
Closed in #83.
