### ISSUE TITLE
Need to think about data integrity

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [FAIRDataPipeline/data-registry#46]
At the moment, the flag on_delete=models.CASCADE is used in various places in the model definitions.

For example:
Deleting a StorageLocation right now will also delete any Objects referencing it. I expect that we want to be more careful about not deleting data.

We should decide where we want to protect model entries using the on_delete=PROTECT flag.

**Comment by richardreeve** [comment]
That's fine I think - at least for the time being. We do want to be able to delete things safely through the web interface though - and I'm not sure what will happen with the cascading deletions there?

Down the road we may want to allow the command line tool to do some cleaning tasks though, which may involve programmatic deletions...
