### ISSUE TITLE
Test data for local registry

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [FAIRDataPipeline/data-registry#51]
Have some sample data in there that users can play with.

**Comment by agbeltran** [comment]
For this, it would be great to provide a script that populates the local registry with some sample data.

**Comment by antony-wilson** [comment]
I could add a `add_sample_data` option to `manage.py`
We could have it that the script populates the registry with the data generated from the two runs that are being used as examples in the paper.

```
python manage.py add_sample_data
```

It may be worth checking the data base first and only allowing the user to add the sample data to an empty database.

**Comment by agbeltran** [comment]
can this be closed @antony-wilson ?

**Comment by RyanJField** [comment]
Test data available and tested.
