### ISSUE TITLE
Server error (500) when trying to load the documentation in a newly installed local registry

### ISSUE THREAD

**Issue by agbeltran** [FAIRDataPipeline/data-registry#53]
After installing the local registry, I get a 500 error when following the documentation link under Links:
http://localhost:8000/docs/

**Comment by alahiff** [comment]
It's trying to open the file `docs/index.md` but doesn't know the full path to `docs` - it's assumed to be `/docs`:

```
  File "/home/andrewlahiff/.scrc/data_management/views.py", line 127, in doc_index
    with open(os.path.join('docs', 'index.md')) as file:

Exception Type: FileNotFoundError at /docs/
Exception Value: [Errno 2] No such file or directory: 'docs/index.md'
```

**Comment by alahiff** [comment]
Strangely in a newly installed local registry I'm not able to reproduce this problem anymore. Is this the same for everyone?

**Comment by nathan-cummings-ukaea** [comment]
I have no problems on my local registry either. @agbeltran, do you still have the issue with an up-to-date install?

**Comment by agbeltran** [comment]
@alahiff @nathan-cummings-ukaea I've just deleted all the content in ```.scrc``` and installed everything again - still getting a 500 error when trying to access:
http://localhost:8000/docs/

maybe you followed some other step to build the documentation that is not specified at https://fairdatapipeline.github.io/docs/local_registry/ ?

**Comment by alahiff** [comment]
I just followed the documentation at https://fairdatapipeline.github.io/docs/local_registry/. I didn't do any other steps.

I don't actually understand why it didn't work for me previously but now it does work. Looking through the commit history I couldn't see any obvious changes that would have corrected this.

**Comment by agbeltran** [comment]
thanks @alahiff - perhaps I'm missing some step to generate html? I only see markdown files under ```.scrc/docs```

**Comment by nathan-cummings-ukaea** [comment]
No, you're right @agbeltran , there is something going on here. I just spun up my server, went to Documentation and got a 500 error. I then changed the debug flag to true to try and figure out why, and the docs loaded up fine. Now I can't replicate the error again!

@agbeltran does it fix the issue to stop and restart the server, or do you never get any luck loading that page at all?

**Comment by agbeltran** [comment]
I'm afraid that stopping and restarting the server hasn't fixed the issue for me - will continue investigating

**Comment by alahiff** [comment]
It seems that you need to run `scripts/run_scrc_server` from inside the `.scrc` directory in order for the docs to work. If you run `.scrc/scripts/run_scrc_server` from your home directory you get the 500 error.

Ideally the `run_scrc_server` script should be modified so that it does a `cd $HOME/.scrc` at the beginning.

**Comment by alahiff** [comment]
I've made an adjustment to `run_scrc_server` (https://github.com/ScottishCovidResponse/data-registry/commit/16f8f689e0987bc1ec9c157ffefa5cc3b02b62df) which I think has fixed the problem.

**Comment by agbeltran** [comment]
thanks, @alahiff, I will test it - indeed running the script from the folder solved the issues locally

**Comment by agbeltran** [comment]
I've just tested this again and it is fixed. Closing. Thank you all.
