### ISSUE TITLE
Server error (500) when clicking in OPTION on the API page

### ISSUE THREAD

**Issue by agbeltran** [FAIRDataPipeline/data-registry#54]
On a newly installed local registry, I'm getting a 500 error when clicking in the ```OPTION``` button in the API page: http://localhost:8000/api/

**Comment by alahiff** [comment]
`data.scrc.uk` has the same problem.

The error is:
```
  File "/home/andrewlahiff/.scrc/data_management/rest/metadata.py", line 8, in determine_metadata
    if view.model.FILTERSET_FIELDS == '__all__':

Exception Type: AttributeError at /api/
Exception Value: 'APIRootView' object has no attribute 'model'
```

**Comment by alahiff** [comment]
The same thing happes with `/api/users`:
```
'UserViewSet' object has no attribute 'model'
```

**Comment by alahiff** [comment]
This ha sbeen resolved in https://github.com/FAIRDataPipeline/data-registry/commit/16bfd36e56e6e9233451fcb5fd5fb4dcd1f0c4cd
