### ISSUE TITLE
Move registry and tag release

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#61]
There are a few things that need to be done before the 1.0 release @alahiff @nathan-cummings-ukaea - https://github.com/ScottishCovidResponse/data-registry/milestone/1 - but some are administrative rather than code changes:

- [x] Move this repo to the FAIRDataPipeline org
- [x] Delete the exist 1.0 and 1.1 tags
- [x] Move the existing remote registry to https://old-data.scrc.uk
- [x] Create a new remote registry with the new schema at https://data.scrc.uk
- [x] Release 1.0-rc1

**Comment by alahiff** [comment]
I've renamed the 1.0 & 1.1 tags (& corresponding releases) to v0.1.0 & v0.1.1.

**Comment by agbeltran** [comment]
Moving the repo will have an impact to the script https://github.com/ScottishCovidResponse/data-registry/blob/master/static/localregistry.sh, possibly others too

**Comment by richardreeve** [comment]
Good point. The sooner we move it and fix any breakages the better then.

**Comment by alahiff** [comment]
The data registry repo is now: https://github.com/FAIRDataPipeline/data-registry/

**Comment by richardreeve** [comment]
@alahiff - @agbeltran has said we have done enough of #24 that we can remove it from the 1.0 milestone - she'll continue the rest later. So I think this means we can release 1.0-rc1 unless there's something new that you think needs fixed immediately?

**Comment by alahiff** [comment]
@richardreeve I think we can make the 1.0-rc1 release now.

**Comment by richardreeve** [comment]
Okay, go for it. If we do that and push it to data.scrc.uk, then we can tell everyone on zulip to update and hope that things will be stable for a while?
