### ISSUE TITLE
Switch testing to github actions

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#68]
Testing was broken (#62) due to changes to Travis. This is temporarily fixed, but we should move to github actions as we have for most of the rest of our repos.

**Comment by alahiff** [comment]
FYI Now that we've moved the repo over to FAIRDataPipeline we've lost all the testing on Travis.

**Comment by richardreeve** [comment]
Okay, once we've release 1.0-rc1, then this will become high priority then I guess!

**Comment by alahiff** [comment]
The Travis config has been removed and tests using GitHub actions have been added.
