### ISSUE TITLE
Fix documentation text for CodeRun.

### ISSUE THREAD

**Issue by agbeltran** [FAIRDataPipeline/data-registry#80]
As raise by @soniamitchell, the CodeRun.code_repo field documentation needs updating:

https://github.com/FAIRDataPipeline/data-registry/blob/20576d87b5b7818a932707feaef9f466174a81b2/data_management/models.py#L419

    `code_repo` (*optional*):  Reference to the `Object` associated with the `CodeRepoRelease` that was run

`CodeRepoRelease` should be `StorageLocation`

**Comment by richardreeve** [comment]
"`StorageLocation` where the code repository is stored", perhaps?

**Comment by agbeltran** [comment]
yes, indeed, thanks @richardreeve
