### ISSUE TITLE
Filtering - documentation & possible improvements

### ISSUE THREAD

**Issue by alahiff** [FAIRDataPipeline/data-registry#91]
We should document how filtering works.

We should also perhaps do some tidying up of the filtering. Even though there is both a RegexFilter https://github.com/FAIRDataPipeline/data-registry/blob/71c17cb8139d56ce54078ea41496c97fbf0a6085/data_management/rest/views.py#L153 and GlobFilter https://github.com/FAIRDataPipeline/data-registry/blob/71c17cb8139d56ce54078ea41496c97fbf0a6085/data_management/rest/views.py#L163 defined, when I try to test it the GlobFilter is always used. Plus the GlobFilter seems to be designed to deal with regular expressions.

There seems to be a problem with the GlobFilter in that it escapes everything, resulting in it being impossible to use standard regular expressions. For example this:
```
http://localhost:8000/api/data_product/?name=fixed-parameters/\d
```
results in this regex being used:
```
\A(fixed\-parameters/\\d)\Z
```
The two slashes in front of the `d` prevent it from working.

**Comment by richardreeve** [comment]
I think we decided last year that simple globbing with * and ** would be enough, and so we never got as far as regexes. We should definitely discuss at 3pm whether to do that, or even do the ** globbing though.

**Comment by alahiff** [comment]
I can confirm that having text after a * does indeed work, e.g.
```
http://localhost:8000/api/data_product/?name=fixed-parameter/*/1
```

**Comment by richardreeve** [comment]
Cool. So we leave this as it is with just normal * globbing, and @soniamitchell will update the DPAPI documentation to say that only normal * globbing exists.

**Comment by alahiff** [comment]
I've removed RegexFilter from the code as it's not being used at all https://github.com/FAIRDataPipeline/data-registry/commit/30e47a4e3ef68e941220d1cad9ed826b4f95b6d3

If we only need normal globbing only then I don't think I need to do anything else. Globbing is already briefly mentioned in https://github.com/FAIRDataPipeline/data-registry/blob/main/docs/api_guide.md.

**Comment by richardreeve** [comment]
It sounds like this can be closed then?
