### ISSUE TITLE
API to find out user id

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/data-registry#93]
In order to get the correct entry from the `user_author_org` table, we need to know what our user id is. Is there an API to do this already? If not can we create one easily? http://localhost:8000/api/users/ gives a "Server Error (500)" when you log in as admin.

**Comment by alahiff** [comment]
Interesting - http://localhost:8000/api/users/ works for me when I'm logged in as admin. This also works:
```
curl -H "Authorization: Token <token>" http://localhost:8000/api/users/
```
where `<token>` is taken from `~/.fair/registry/token`.
```

**Comment by richardreeve** [comment]
@DennisReddyhoff - do you want to check this again? It was you that was having this problem...

**Comment by soniamitchell** [comment]
Following a brief chat with @richardreeve.. assuming the user id is the URL of the admin entry in the User table. This works in R. I'm able to get the URL, generate a new_user_author_org entry, and attach it to objects. 

Prior to my week off I was under the impression this was going to change though!

**Comment by richardreeve** [comment]
We're waiting on the outcome of #90 to see if this (the UserAUthorOrg bit) changes or not. For now it stays.

**Comment by richardreeve** [comment]
So it will change, and we'll lose the ObjectAuthorOrg table.

**Comment by richardreeve** [comment]
@alahiff - I presume we can close this now as no-one can reproduce the problem.

**Comment by alahiff** [comment]
Ok, closing
