### ISSUE TITLE
Enable OPTIONS for Users table

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/data-registry#94]

**Comment by alahiff** [comment]
I've made a small change https://github.com/FAIRDataPipeline/data-registry/commit/16bfd36e56e6e9233451fcb5fd5fb4dcd1f0c4cd to prevent the errors which occur whenever a model doesn't allow filtering.

Now OPTIONS for the `User` table give this:
```
{
    "name": "User List",
    "description": "API views (GET only) for the User model.",
    "renders": [
        "application/json",
        "text/html"
    ],
    "parses": [
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ]
}
```
Is this ok? If it is I might improve my fix slightly, but the result will be the same.

**Comment by soniamitchell** [comment]
As well as the `parses` section, there's usually a `actions:POST` section. That's the bit I'm after really. If it's not a goer, don't worry too much about it though.

**Comment by alahiff** [comment]
POST is not supported for this table.

**Comment by soniamitchell** [comment]
This is true, but I was under the impression it would be eventually? I could be wrong though! -- If I am, I don't need OPTIONS.

**Comment by alahiff** [comment]
If we decide to drop the `UserAuthor` table then yes, it would eventually. For the moment though we're going to keep `UserAuthor`.

**Comment by soniamitchell** [comment]
Cool, happy to close this Issue then 👍
